// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '.' }],

  //   docs: [
  //   {
  //     type: 'category',
  //     label: 'Materias',
  //     items: ['materias/introduccion', 'materias/crear-materia', 'materias/editar-materia', {type: 'category', label: 'Curso', items: ['materias/curso/crear-curso', 'materias/curso/editar-curso']}],
      
  //   },
  // ],
};


export default sidebars;
